# Generated by Django 3.2 on 2021-05-05 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210505_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('-created_at',), 'verbose_name': 'brand', 'verbose_name_plural': '5. brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-created_at',), 'verbose_name': 'category', 'verbose_name_plural': '4. categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'get_latest_by': 'created_at', 'verbose_name_plural': '6. products'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'ordering': ('-id',), 'verbose_name_plural': '7. productsAttributes'},
        ),
    ]
