# Generated by Django 3.2 on 2021-05-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210506_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url4',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='image_url1',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='image_url2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='image_url3',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='image_url4',
            field=models.URLField(blank=True),
        ),
    ]
