# Generated by Django 3.2 on 2021-05-10 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'get_latest_by': 'created_at', 'verbose_name_plural': '3. Products'},
        ),
    ]
