# Generated by Django 3.1.6 on 2021-07-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_useraddressbook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name_plural': '10. Reviews'},
        ),
        migrations.AlterModelOptions(
            name='useraddressbook',
            options={'verbose_name_plural': '12. AddressBook'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name_plural': '11. Wishlist'},
        ),
    ]
