# Generated by Django 3.2 on 2021-04-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='your_name',
            field=models.EmailField(max_length=254),
        ),
    ]
