# Generated by Django 3.2 on 2021-04-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_commentmodel_your_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='your_email',
            field=models.EmailField(default='fafopalermo@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='your_name',
            field=models.CharField(max_length=100),
        ),
    ]
