# Generated by Django 3.2 on 2021-04-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210427_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='your_email',
            field=models.EmailField(max_length=254),
        ),
    ]
