# Generated by Django 3.2 on 2021-04-29 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_commentmodel_your_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_blog', to='blog.blogmodel'),
        ),
    ]
