# Generated by Django 3.2 on 2021-05-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='image_one',
        ),
        migrations.RemoveField(
            model_name='section',
            name='image_two',
        ),
        migrations.AddField(
            model_name='section',
            name='icon_url',
            field=models.URLField(blank=True),
        ),
    ]
