# Generated by Django 3.2 on 2021-05-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210505_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='section',
            name='icon_class',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
