# Generated by Django 3.2 on 2021-05-05 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210505_1551'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Teammate',
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('-id',), 'verbose_name': 'banner', 'verbose_name_plural': '1. banners'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('created_at',), 'verbose_name': 'section', 'verbose_name_plural': '2. sections'},
        ),
        migrations.AlterModelOptions(
            name='teammate',
            options={'ordering': ('-id',), 'verbose_name': '3. teammate', 'verbose_name_plural': 'teammates'},
        ),
    ]
