# Generated by Django 3.2 on 2021-05-05 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210505_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('-id',), 'verbose_name': 'Banner', 'verbose_name_plural': '1. Banners'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('created_at',), 'verbose_name': 'Section', 'verbose_name_plural': '2. Sections'},
        ),
        migrations.AlterModelOptions(
            name='teammate',
            options={'ordering': ('-id',), 'verbose_name': 'Teammate', 'verbose_name_plural': '3. Teammates'},
        ),
    ]
