# Generated by Django 3.2 on 2021-05-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_banner_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='img',
            new_name='image',
        ),
    ]
